#!/bin/bash
function config {
   /usr/bin/git --git-dir=$HOME/.config-sync/ --work-tree=$HOME $@
}
mkdir -p .config-backup
cfg checkout
if [ $? = 0 ]; then
  echo "Checked out config.";
  else
    echo "Backing up pre-existing dot files.";
    cfg checkout 2>&1 | egrep "\s+\." | awk {'print $1'} | xargs -I{} mv {} .config-backup/{}
fi; 
cfg config --local status.showUntrackedFiles no
